-- MySQL Script generated by MySQL Workbench
-- sáb 02 ene 2016 22:04:59 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CPE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CPE` ;

-- -----------------------------------------------------
-- Schema CPE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CPE` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `CPE` ;

-- -----------------------------------------------------
-- Table `CPE`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPE`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `CPE`.`Equipo` (
  `placa` INT NOT NULL COMMENT '',
  `serie` VARCHAR(45) NOT NULL COMMENT '',
  `marca` VARCHAR(45) NOT NULL COMMENT '',
  `modelo` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '',
  `estado` VARCHAR(45) NOT NULL COMMENT '',
  `anio_ingreso` INT(4) NULL COMMENT '',
  `observacion` MEDIUMTEXT NULL COMMENT '',
  PRIMARY KEY (`placa`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPE`.`Computadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPE`.`Computadora` ;

CREATE TABLE IF NOT EXISTS `CPE`.`Computadora` (
  `placa` INT NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `procesador` VARCHAR(45) NULL COMMENT '',
  `cant_memoria_hhd` VARCHAR(45) NULL COMMENT '',
  `criterio` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`placa`)  COMMENT '',
  CONSTRAINT `fk_Computadora_Equipo`
    FOREIGN KEY (`placa`)
    REFERENCES `CPE`.`Equipo` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPE`.`Impresora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPE`.`Impresora` ;

CREATE TABLE IF NOT EXISTS `CPE`.`Impresora` (
  `placa` INT NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `consumible` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`placa`)  COMMENT '',
  CONSTRAINT `fk_Impresora_Equipo1`
    FOREIGN KEY (`placa`)
    REFERENCES `CPE`.`Equipo` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPE`.`proyector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPE`.`proyector` ;

CREATE TABLE IF NOT EXISTS `CPE`.`proyector` (
  `placa` INT NOT NULL COMMENT '',
  `funcionalidad` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`placa`)  COMMENT '',
  CONSTRAINT `fk_proyector_Equipo1`
    FOREIGN KEY (`placa`)
    REFERENCES `CPE`.`Equipo` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPE`.`Oficina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPE`.`Oficina` ;

CREATE TABLE IF NOT EXISTS `CPE`.`Oficina` (
  `idOficina` INT NOT NULL COMMENT '',
  `nombreOficina` VARCHAR(45) NOT NULL COMMENT '',
  `unidad` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idOficina`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPE`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPE`.`Persona` ;

CREATE TABLE IF NOT EXISTS `CPE`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombrePersona` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idPersona`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPE`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPE`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `CPE`.`Usuario` (
  `idUsuario` INT NOT NULL COMMENT '',
  `nombreUsuario` VARCHAR(45) NOT NULL COMMENT '',
  `contrasena` VARCHAR(45) NOT NULL COMMENT '',
  `idPersona` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '',
  INDEX `fk_Usuario_Persona1_idx` (`idPersona` ASC)  COMMENT '',
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `CPE`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPE`.`Bitacora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPE`.`Bitacora` ;

CREATE TABLE IF NOT EXISTS `CPE`.`Bitacora` (
  `idBitacora` INT NOT NULL COMMENT '',
  `nombreTabla` VARCHAR(45) NULL COMMENT '',
  `horaTransaccion` VARCHAR(45) NOT NULL COMMENT '',
  `fechaTransaccion` DATE NOT NULL COMMENT '',
  `transaccion` VARCHAR(45) NOT NULL COMMENT '',
  `nuevoValor` MEDIUMTEXT NULL COMMENT '',
  `valorAnterior` MEDIUMTEXT NULL COMMENT '',
  `idUsuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idBitacora`)  COMMENT '',
  INDEX `fk_Bitacora_Usuario1_idx` (`idUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Bitacora_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `CPE`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPE`.`OtroEquipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPE`.`OtroEquipo` ;

CREATE TABLE IF NOT EXISTS `CPE`.`OtroEquipo` (
  `placa` INT NOT NULL COMMENT '',
  `nombreEquipo` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`placa`)  COMMENT '',
  CONSTRAINT `fk_OtroEquipo_Equipo1`
    FOREIGN KEY (`placa`)
    REFERENCES `CPE`.`Equipo` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPE`.`Telefonia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPE`.`Telefonia` ;

CREATE TABLE IF NOT EXISTS `CPE`.`Telefonia` (
  `placa` INT NOT NULL COMMENT '',
  `extension` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`placa`)  COMMENT '',
  CONSTRAINT `fk_Telefonia_Equipo1`
    FOREIGN KEY (`placa`)
    REFERENCES `CPE`.`Equipo` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPE`.`Prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPE`.`Prestamo` ;

CREATE TABLE IF NOT EXISTS `CPE`.`Prestamo` (
  `idPrestamo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `placa` INT NULL COMMENT '',
  `tipoEquipo` VARCHAR(45) NULL COMMENT '',
  `idOficina` INT NULL COMMENT '',
  `idPersona` INT NULL COMMENT '',
  `fechaPrestamo` DATE NULL COMMENT '',
  `estado` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idPrestamo`)  COMMENT '',
  INDEX `fk_Prestamo_Equipo1_idx` (`placa` ASC)  COMMENT '',
  INDEX `fk_Prestamo_Oficina1_idx` (`idOficina` ASC)  COMMENT '',
  INDEX `fk_Prestamo_Persona1_idx` (`idPersona` ASC)  COMMENT '',
  CONSTRAINT `fk_Prestamo_Equipo1`
    FOREIGN KEY (`placa`)
    REFERENCES `CPE`.`Equipo` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Oficina1`
    FOREIGN KEY (`idOficina`)
    REFERENCES `CPE`.`Oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `CPE`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
